running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "gcvspline._gcvspl" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline' to include_dirs.
  adding 'build/src.linux-x86_64-3.6/gcvspline/_gcvspl-f2pywrappers.f' to sources.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
C compiler: /home/charles/miniconda3/envs/py36/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC

creating /tmp/tmpapsycq51/tmp
creating /tmp/tmpapsycq51/tmp/tmpapsycq51
compile options: '-MMD -MF /tmp/tmpapsycq51/file.c.d -c'
x86_64-conda_cos6-linux-gnu-cc: /tmp/tmpapsycq51/file.c
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
Found executable /home/charles/miniconda3/envs/py36/bin/x86_64-conda_cos6-linux-gnu-ld
Found executable /home/charles/miniconda3/envs/py36/bin/x86_64-conda_cos6-linux-gnu-ar
Found executable /home/charles/miniconda3/envs/py36/bin/x86_64-conda_cos6-linux-gnu-ranlib
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'gcvspline._gcvspl' extension
compiling C sources
C compiler: /home/charles/miniconda3/envs/py36/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC

compile options: '-Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline -I/home/charles/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/include -I/home/charles/miniconda3/envs/py36/include/python3.6m -c'
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
compile options: '-Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline -I/home/charles/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/include -I/home/charles/miniconda3/envs/py36/include/python3.6m -c'
gfortran:f77: build/src.linux-x86_64-3.6/gcvspline/_gcvspl-f2pywrappers.f
gfortran:f77: gcvspline/gcvspl.f
gcvspline/gcvspl.f:723:5:

    20 jj = 0
     1
Warning: Label 20 at (1) defined but not used [-Wunused-label]
/usr/bin/gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o build/temp.linux-x86_64-3.6/gcvspline/gcvspl.o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvspl-f2pywrappers.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib -lgfortran -o build/lib.linux-x86_64-3.6/gcvspline/_gcvspl.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `int_from_pyobj':
_gcvsplmodule.c:(.text+0x29): undefined reference to `PyNumber_Long'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a): undefined reference to `PyLong_AsLong'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x6f): undefined reference to `PyComplex_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7a): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x99): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb0): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xcd): undefined reference to `PyLong_AsLong'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xf4): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x102): undefined reference to `PyErr_Clear'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x165): undefined reference to `PySequence_Check'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x178): undefined reference to `PySequence_GetItem'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_splderv':
_gcvsplmodule.c:(.text+0x1bb): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2bb): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3eb): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3fa): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x417): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x5ad): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x5e2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x5ff): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x70a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x766): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x788): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7ab): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7c5): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7e7): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_trinv':
_gcvsplmodule.c:(.text+0x827): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x8b1): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x9b9): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xa5a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xa77): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xae7): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb38): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb45): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb62): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_bansol':
_gcvsplmodule.c:(.text+0xbab): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xc86): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xea6): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xed4): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xf6a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xf83): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xfdf): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xff2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x100f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1104): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1121): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1161): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_bandet':
_gcvsplmodule.c:(.text+0x1197): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1203): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x12e6): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x13a4): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x13c2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x13df): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x140b): undefined reference to `Py_BuildValue'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `double_from_pyobj':
_gcvsplmodule.c:(.text+0x1457): undefined reference to `PyFloat_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1465): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1495): undefined reference to `PyNumber_Float'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x14d7): undefined reference to `PyComplex_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x14e2): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1501): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1518): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1534): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1542): undefined reference to `PyErr_Clear'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x15a4): undefined reference to `PySequence_Check'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x15b7): undefined reference to `PySequence_GetItem'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_search':
_gcvsplmodule.c:(.text+0x15fb): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1673): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1722): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x173b): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x17c2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x17ea): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1852): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_splder':
_gcvsplmodule.c:(.text+0x189b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1978): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1a2a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1a43): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1b9e): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1c4d): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1c83): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1cbe): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1cdb): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1cf0): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1d11): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_splc':
_gcvsplmodule.c:(.text+0x1d4b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1f9a): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x212a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2143): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2152): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x216f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2347): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2362): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x237f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x25d4): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2690): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26ad): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26b8): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26d5): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26e0): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26fd): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x28c2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x28f8): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x295a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2973): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x297b): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2998): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_prep':
_gcvsplmodule.c:(.text+0x29db): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2a76): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2b2a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2b43): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2bea): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2ca4): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2cff): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d1c): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d34): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d48): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d61): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_basis':
_gcvsplmodule.c:(.text+0x2d9b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2e3b): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2f18): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2f72): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2f8b): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x307a): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x30d2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x30ef): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3150): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3174): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x31a9): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x31c6): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_gcvspl':
_gcvsplmodule.c:(.text+0x31fb): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x336e): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3482): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x349b): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x34aa): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x34c7): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x35ed): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3870): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x38a2): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3900): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3919): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3921): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x393e): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3949): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3966): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3971): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x398e): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `PyInit__gcvspl':
_gcvsplmodule.c:(.text+0x39b2): undefined reference to `PyModule_Create2'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x39b9): undefined reference to `PyType_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x39d4): undefined reference to `PyImport_ImportModule'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x39f0): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a14): undefined reference to `PyCapsule_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a21): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a31): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a4c): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a52): undefined reference to `PyErr_Print'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a65): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a7f): undefined reference to `PyCapsule_GetPointer'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3ae8): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3af4): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b04): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b15): undefined reference to `PyModule_GetDict'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b25): undefined reference to `PyBytes_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b38): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b45): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b5b): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b6c): undefined reference to `PyErr_NewException'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3bbf): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3bd5): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3bfa): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c07): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c1a): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c2a): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c4f): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c5c): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c6f): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c7f): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3ca4): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cb1): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cc4): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cda): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3ce5): undefined reference to `PyErr_Format'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cf3): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d0f): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d1a): undefined reference to `PyErr_Format'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d21): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d2d): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d3d): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d5f): undefined reference to `PyExc_AttributeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d6f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d76): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d8e): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d9e): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3da5): undefined reference to `PyExc_ImportError'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_repr':
fortranobject.c:(.text+0x2f): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: fortranobject.c:(.text+0x38): undefined reference to `PyErr_Clear'
/usr/bin/ld: fortranobject.c:(.text+0x57): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: fortranobject.c:(.text+0x8e): undefined reference to `PyUnicode_FromFormat'
/usr/bin/ld: fortranobject.c:(.text+0xaf): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `format_def':
fortranobject.c:(.text+0xe8): undefined reference to `PyOS_snprintf'
/usr/bin/ld: fortranobject.c:(.text+0x146): undefined reference to `PyOS_snprintf'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_dealloc':
fortranobject.c:(.text+0x1e0): undefined reference to `PyMem_Free'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `check_and_fix_dimensions':
fortranobject.c:(.text+0x717): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x723): undefined reference to `PyErr_SetString'
/usr/bin/ld: fortranobject.c:(.text+0x7e5): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x7f7): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x80b): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x81d): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x85a): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x865): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x91f): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x937): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x948): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x95d): undefined reference to `PyErr_Format'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_call':
fortranobject.c:(.text+0xa23): undefined reference to `PyExc_TypeError'
/usr/bin/ld: fortranobject.c:(.text+0xa35): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0xa43): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: fortranobject.c:(.text+0xa55): undefined reference to `PyErr_Format'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyDict_SetItemString':
fortranobject.c:(.text+0xa67): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: fortranobject.c:(.text+0xa97): undefined reference to `PyErr_Occurred'
/usr/bin/ld: fortranobject.c:(.text+0xaa2): undefined reference to `PyErr_Print'
/usr/bin/ld: fortranobject.c:(.text+0xaa8): undefined reference to `PyErr_Clear'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `PyFortranObject_NewAsAttr':
fortranobject.c:(.text+0xad2): undefined reference to `_PyObject_New'
/usr/bin/ld: fortranobject.c:(.text+0xae0): undefined reference to `PyDict_New'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `PyFortranObject_New':
fortranobject.c:(.text+0xb3b): undefined reference to `_PyObject_New'
/usr/bin/ld: fortranobject.c:(.text+0xb4d): undefined reference to `PyDict_New'
/usr/bin/ld: fortranobject.c:(.text+0xc26): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `array_from_pyobj':
fortranobject.c:(.text+0xd2b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0xdd4): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: fortranobject.c:(.text+0x105c): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0x134b): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x1357): undefined reference to `PyErr_SetString'
/usr/bin/ld: fortranobject.c:(.text+0x168b): undefined reference to `PyExc_TypeError'
/usr/bin/ld: fortranobject.c:(.text+0x169e): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_setattr':
fortranobject.c:(.text+0x179d): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0x1916): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: fortranobject.c:(.text+0x1992): undefined reference to `PyDict_New'
/usr/bin/ld: fortranobject.c:(.text+0x19b5): undefined reference to `PyDict_DelItemString'
/usr/bin/ld: fortranobject.c:(.text+0x19c7): undefined reference to `PyExc_AttributeError'
/usr/bin/ld: fortranobject.c:(.text+0x19d7): undefined reference to `PyErr_SetString'
/usr/bin/ld: fortranobject.c:(.text+0x1afe): undefined reference to `PyExc_AttributeError'
/usr/bin/ld: fortranobject.c:(.text+0x1b11): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyCapsule_FromVoidPtr':
fortranobject.c:(.text+0x1b8b): undefined reference to `PyCapsule_New'
/usr/bin/ld: fortranobject.c:(.text+0x1ba7): undefined reference to `PyErr_Clear'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_getattr':
fortranobject.c:(.text+0x1bf5): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: fortranobject.c:(.text+0x1dbb): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: fortranobject.c:(.text+0x1dca): undefined reference to `PyObject_GenericGetAttr'
/usr/bin/ld: fortranobject.c:(.text+0x1df9): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: fortranobject.c:(.text+0x1e39): undefined reference to `PyMem_Malloc'
/usr/bin/ld: fortranobject.c:(.text+0x1e84): undefined reference to `PyOS_snprintf'
/usr/bin/ld: fortranobject.c:(.text+0x1f27): undefined reference to `PyUnicode_FromStringAndSize'
/usr/bin/ld: fortranobject.c:(.text+0x1f33): undefined reference to `PyMem_Free'
/usr/bin/ld: fortranobject.c:(.text+0x1f3f): undefined reference to `PyUnicode_Concat'
/usr/bin/ld: fortranobject.c:(.text+0x2028): undefined reference to `PyMem_Free'
/usr/bin/ld: fortranobject.c:(.text+0x2033): undefined reference to `PyUnicode_Concat'
/usr/bin/ld: fortranobject.c:(.text+0x20e9): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: fortranobject.c:(.text+0x2102): undefined reference to `PyErr_NoMemory'
/usr/bin/ld: fortranobject.c:(.text+0x21d3): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0x21f8): undefined reference to `PyOS_snprintf'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyCapsule_AsVoidPtr':
fortranobject.c:(.text+0x2238): undefined reference to `PyCapsule_GetPointer'
/usr/bin/ld: fortranobject.c:(.text+0x2257): undefined reference to `PyErr_Clear'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyCapsule_Check':
fortranobject.c:(.text+0x2273): undefined reference to `PyCapsule_Type'
collect2: error: ld returned 1 exit status
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `int_from_pyobj':
_gcvsplmodule.c:(.text+0x29): undefined reference to `PyNumber_Long'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a): undefined reference to `PyLong_AsLong'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x6f): undefined reference to `PyComplex_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7a): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x99): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb0): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xcd): undefined reference to `PyLong_AsLong'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xf4): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x102): undefined reference to `PyErr_Clear'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x165): undefined reference to `PySequence_Check'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x178): undefined reference to `PySequence_GetItem'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_splderv':
_gcvsplmodule.c:(.text+0x1bb): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2bb): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3eb): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3fa): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x417): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x5ad): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x5e2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x5ff): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x70a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x766): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x788): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7ab): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7c5): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x7e7): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_trinv':
_gcvsplmodule.c:(.text+0x827): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x8b1): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x9b9): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xa5a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xa77): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xae7): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb38): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb45): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xb62): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_bansol':
_gcvsplmodule.c:(.text+0xbab): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xc86): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xea6): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xed4): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xf6a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xf83): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xfdf): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0xff2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x100f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1104): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1121): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1161): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_bandet':
_gcvsplmodule.c:(.text+0x1197): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1203): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x12e6): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x13a4): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x13c2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x13df): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x140b): undefined reference to `Py_BuildValue'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `double_from_pyobj':
_gcvsplmodule.c:(.text+0x1457): undefined reference to `PyFloat_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1465): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1495): undefined reference to `PyNumber_Float'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x14d7): undefined reference to `PyComplex_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x14e2): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1501): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1518): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1534): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1542): undefined reference to `PyErr_Clear'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x15a4): undefined reference to `PySequence_Check'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x15b7): undefined reference to `PySequence_GetItem'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_search':
_gcvsplmodule.c:(.text+0x15fb): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1673): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1722): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x173b): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x17c2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x17ea): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1852): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_splder':
_gcvsplmodule.c:(.text+0x189b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1978): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1a2a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1a43): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1b9e): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1c4d): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1c83): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1cbe): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1cdb): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1cf0): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1d11): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_splc':
_gcvsplmodule.c:(.text+0x1d4b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x1f9a): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x212a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2143): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2152): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x216f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2347): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2362): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x237f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x25d4): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2690): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26ad): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26b8): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26d5): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26e0): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x26fd): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x28c2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x28f8): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x295a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2973): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x297b): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2998): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_prep':
_gcvsplmodule.c:(.text+0x29db): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2a76): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2b2a): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2b43): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2bea): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2ca4): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2cff): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d1c): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d34): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d48): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2d61): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_basis':
_gcvsplmodule.c:(.text+0x2d9b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2e3b): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2f18): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2f72): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x2f8b): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x307a): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x30d2): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x30ef): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3150): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3174): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x31a9): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x31c6): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `f2py_rout__gcvspl_gcvspl':
_gcvsplmodule.c:(.text+0x31fb): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x336e): undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3482): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x349b): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x34aa): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x34c7): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x35ed): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3870): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x38a2): undefined reference to `Py_BuildValue'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3900): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3919): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3921): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x393e): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3949): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3966): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3971): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x398e): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o: in function `PyInit__gcvspl':
_gcvsplmodule.c:(.text+0x39b2): undefined reference to `PyModule_Create2'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x39b9): undefined reference to `PyType_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x39d4): undefined reference to `PyImport_ImportModule'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x39f0): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a14): undefined reference to `PyCapsule_Type'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a21): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a31): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a4c): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a52): undefined reference to `PyErr_Print'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a65): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3a7f): undefined reference to `PyCapsule_GetPointer'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3ae8): undefined reference to `PyErr_Occurred'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3af4): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b04): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b15): undefined reference to `PyModule_GetDict'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b25): undefined reference to `PyBytes_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b38): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b45): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b5b): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3b6c): undefined reference to `PyErr_NewException'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3bbf): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3bd5): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3bfa): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c07): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c1a): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c2a): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c4f): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c5c): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c6f): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3c7f): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3ca4): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cb1): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cc4): undefined reference to `PyObject_SetAttrString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cda): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3ce5): undefined reference to `PyErr_Format'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3cf3): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d0f): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d1a): undefined reference to `PyErr_Format'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d21): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d2d): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d3d): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d5f): undefined reference to `PyExc_AttributeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d6f): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d76): undefined reference to `PyExc_ImportError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d8e): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3d9e): undefined reference to `PyErr_SetString'
/usr/bin/ld: _gcvsplmodule.c:(.text+0x3da5): undefined reference to `PyExc_ImportError'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_repr':
fortranobject.c:(.text+0x2f): undefined reference to `PyObject_GetAttrString'
/usr/bin/ld: fortranobject.c:(.text+0x38): undefined reference to `PyErr_Clear'
/usr/bin/ld: fortranobject.c:(.text+0x57): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: fortranobject.c:(.text+0x8e): undefined reference to `PyUnicode_FromFormat'
/usr/bin/ld: fortranobject.c:(.text+0xaf): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `format_def':
fortranobject.c:(.text+0xe8): undefined reference to `PyOS_snprintf'
/usr/bin/ld: fortranobject.c:(.text+0x146): undefined reference to `PyOS_snprintf'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_dealloc':
fortranobject.c:(.text+0x1e0): undefined reference to `PyMem_Free'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `check_and_fix_dimensions':
fortranobject.c:(.text+0x717): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x723): undefined reference to `PyErr_SetString'
/usr/bin/ld: fortranobject.c:(.text+0x7e5): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x7f7): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x80b): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x81d): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x85a): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x865): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x91f): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x937): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0x948): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x95d): undefined reference to `PyErr_Format'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_call':
fortranobject.c:(.text+0xa23): undefined reference to `PyExc_TypeError'
/usr/bin/ld: fortranobject.c:(.text+0xa35): undefined reference to `PyErr_Format'
/usr/bin/ld: fortranobject.c:(.text+0xa43): undefined reference to `PyExc_RuntimeError'
/usr/bin/ld: fortranobject.c:(.text+0xa55): undefined reference to `PyErr_Format'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyDict_SetItemString':
fortranobject.c:(.text+0xa67): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: fortranobject.c:(.text+0xa97): undefined reference to `PyErr_Occurred'
/usr/bin/ld: fortranobject.c:(.text+0xaa2): undefined reference to `PyErr_Print'
/usr/bin/ld: fortranobject.c:(.text+0xaa8): undefined reference to `PyErr_Clear'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `PyFortranObject_NewAsAttr':
fortranobject.c:(.text+0xad2): undefined reference to `_PyObject_New'
/usr/bin/ld: fortranobject.c:(.text+0xae0): undefined reference to `PyDict_New'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `PyFortranObject_New':
fortranobject.c:(.text+0xb3b): undefined reference to `_PyObject_New'
/usr/bin/ld: fortranobject.c:(.text+0xb4d): undefined reference to `PyDict_New'
/usr/bin/ld: fortranobject.c:(.text+0xc26): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `array_from_pyobj':
fortranobject.c:(.text+0xd2b): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0xdd4): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: fortranobject.c:(.text+0x105c): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0x134b): undefined reference to `PyExc_ValueError'
/usr/bin/ld: fortranobject.c:(.text+0x1357): undefined reference to `PyErr_SetString'
/usr/bin/ld: fortranobject.c:(.text+0x168b): undefined reference to `PyExc_TypeError'
/usr/bin/ld: fortranobject.c:(.text+0x169e): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_setattr':
fortranobject.c:(.text+0x179d): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0x1916): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: fortranobject.c:(.text+0x1992): undefined reference to `PyDict_New'
/usr/bin/ld: fortranobject.c:(.text+0x19b5): undefined reference to `PyDict_DelItemString'
/usr/bin/ld: fortranobject.c:(.text+0x19c7): undefined reference to `PyExc_AttributeError'
/usr/bin/ld: fortranobject.c:(.text+0x19d7): undefined reference to `PyErr_SetString'
/usr/bin/ld: fortranobject.c:(.text+0x1afe): undefined reference to `PyExc_AttributeError'
/usr/bin/ld: fortranobject.c:(.text+0x1b11): undefined reference to `PyErr_SetString'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyCapsule_FromVoidPtr':
fortranobject.c:(.text+0x1b8b): undefined reference to `PyCapsule_New'
/usr/bin/ld: fortranobject.c:(.text+0x1ba7): undefined reference to `PyErr_Clear'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `fortran_getattr':
fortranobject.c:(.text+0x1bf5): undefined reference to `PyDict_GetItemString'
/usr/bin/ld: fortranobject.c:(.text+0x1dbb): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: fortranobject.c:(.text+0x1dca): undefined reference to `PyObject_GenericGetAttr'
/usr/bin/ld: fortranobject.c:(.text+0x1df9): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: fortranobject.c:(.text+0x1e39): undefined reference to `PyMem_Malloc'
/usr/bin/ld: fortranobject.c:(.text+0x1e84): undefined reference to `PyOS_snprintf'
/usr/bin/ld: fortranobject.c:(.text+0x1f27): undefined reference to `PyUnicode_FromStringAndSize'
/usr/bin/ld: fortranobject.c:(.text+0x1f33): undefined reference to `PyMem_Free'
/usr/bin/ld: fortranobject.c:(.text+0x1f3f): undefined reference to `PyUnicode_Concat'
/usr/bin/ld: fortranobject.c:(.text+0x2028): undefined reference to `PyMem_Free'
/usr/bin/ld: fortranobject.c:(.text+0x2033): undefined reference to `PyUnicode_Concat'
/usr/bin/ld: fortranobject.c:(.text+0x20e9): undefined reference to `PyDict_SetItemString'
/usr/bin/ld: fortranobject.c:(.text+0x2102): undefined reference to `PyErr_NoMemory'
/usr/bin/ld: fortranobject.c:(.text+0x21d3): undefined reference to `_Py_NoneStruct'
/usr/bin/ld: fortranobject.c:(.text+0x21f8): undefined reference to `PyOS_snprintf'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyCapsule_AsVoidPtr':
fortranobject.c:(.text+0x2238): undefined reference to `PyCapsule_GetPointer'
/usr/bin/ld: fortranobject.c:(.text+0x2257): undefined reference to `PyErr_Clear'
/usr/bin/ld: build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o: in function `F2PyCapsule_Check':
fortranobject.c:(.text+0x2273): undefined reference to `PyCapsule_Type'
collect2: error: ld returned 1 exit status/home/charles/miniconda3/envs/py36/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/home/charles/miniconda3/envs/py36/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)

error: Command "/usr/bin/gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvsplmodule.o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/fortranobject.o build/temp.linux-x86_64-3.6/gcvspline/gcvspl.o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/gcvspline/_gcvspl-f2pywrappers.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib -lgfortran -o build/lib.linux-x86_64-3.6/gcvspline/_gcvspl.cpython-36m-x86_64-linux-gnu.so" failed with exit status 1
